description: >
  This command sends deployment insights to New Relic
# What will this command do?
# Descriptions should be short, simple, and clear.
parameters:
  account_id:
    type: string
    description: "NewRelic accountId"
  insert_key:
    type: string
    description: "NewRelic Insert Key"
steps:
  - run:
      name: Send Deployment Insights
      command: |
            echo <<parameters.account_id>>
            echo <<parameters.insert_key>>
            curl -X POST "https://insights-collector.newrelic.com/v1/accounts/${new_relic_account_id_dev}/events" \
            -H "X-Insert-Key: ${new_relic_insert_key_dev}" \
            -H "Content-Type: application/json" \
            -d \
            "[{
              \"eventType\": \"deployment\",
              \"revision\": \"${CIRCLE_SHA1}\",
              \"job\": \"${CIRCLE_JOB}\",
              \"repo\": \"${CIRCLE_PROJECT_REPONAME}\",
              \"user\": \"${CIRCLE_USERNAME}\",
              \"workflowId\": \"${CIRCLE_WORKFLOW_ID}\",
              \"buildUrl\": \"${CIRCLE_BUILD_URL}\",
              \"buildNum\": \"${CIRCLE_BUILD_NUM}\",
              \"branch\": \"${CIRCLE_BRANCH}\"
            }]"
